name: Publish Docs to GitHub Pages
on:
  push:
    branches:
      - PicoW
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Configure Project
        uses: threeal/cmake-action@v1.3.0
      - name: Build Project Documentation
        runs: cmake --build build --target doxygen
      - name: Publish generated content to GitHub Pages
        uses: tsunematsu21/actions-publish-gh-pages@v1.0.2
        with:
          dir: build/html
          branch: gh-pages
          token: ${{ secrets.ACCESS_TOKEN }}
